#pragma once

#define IDI_APP_ICON 101
#define ID_MENU_EXIT 1001
#define ID_MENU_AUTOSTART 1002
#define ID_MENU_ENABLED 1003
#define ID_MENU_MODE_HARDWARE 1101
#define ID_MENU_MODE_SOFTWARE 1102

#define WM_USER_SHELLICON (WM_USER + 1)
#define WM_USER_BRIGHTNESS_CHANGED (WM_USER + 2)
