#pragma once

#define IDI_APP_ICON 101
#define IDR_INTER_REGULAR 201
#define IDR_INTER_MEDIUM 202
#define IDR_INTER_SEMIBOLD 203
#define IDR_INTER_LICENSE 204
#define ID_MENU_EXIT 1001
#define ID_MENU_AUTOSTART 1002
#define ID_MENU_SHOW 1003
#define ID_MENU_TOGGLE_ENABLED 1004

#define WM_USER_SHELLICON (WM_USER + 1)
#define WM_USER_SHOW_POPUP (WM_USER + 2)
